package tube.entities;
// Generated Oct 6, 2016 4:59:27 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "youtubeDB", uniqueConstraints = { @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "username") })
public class User implements java.io.Serializable {

	private Integer id;
	private String email;
	private boolean isAdmin;
	private boolean isBanned;
	private String password;
	private String username;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Playlist> playlists = new HashSet<Playlist>(0);
	private Set<User> usersForUserId = new HashSet<User>(0);
	private Set<UserLikes> userLikes = new HashSet<UserLikes>(0);
	private Set<Video> videos = new HashSet<Video>(0);
	private Set<User> usersForSubscribeUserId = new HashSet<User>(0);

	public User() {
	}

	public User(String email, boolean isAdmin, boolean isBanned, String password, String username) {
		this.email = email;
		this.isAdmin = isAdmin;
		this.isBanned = isBanned;
		this.password = password;
		this.username = username;
	}

	public User(String email, boolean isAdmin, boolean isBanned, String password, String username,
			Set<Comment> comments, Set<Playlist> playlists, Set<User> usersForUserId, Set<UserLikes> userLikes,
			Set<Video> videos, Set<User> usersForSubscribeUserId) {
		this.email = email;
		this.isAdmin = isAdmin;
		this.isBanned = isBanned;
		this.password = password;
		this.username = username;
		this.comments = comments;
		this.playlists = playlists;
		this.usersForUserId = usersForUserId;
		this.userLikes = userLikes;
		this.videos = videos;
		this.usersForSubscribeUserId = usersForSubscribeUserId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", unique = true, nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "isAdmin", nullable = false)
	public boolean isIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	@Column(name = "isBanned", nullable = false)
	public boolean isIsBanned() {
		return this.isBanned;
	}

	public void setIsBanned(boolean isBanned) {
		this.isBanned = isBanned;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Comment> getCommentses() {
		return this.comments;
	}

	public void setCommentses(Set<Comment> commentses) {
		this.comments = commentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Playlist> getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set<Playlist> playlists) {
		this.playlists = playlists;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "subscribers", catalog = "youtubeDB", uniqueConstraints = {
			@UniqueConstraint(columnNames = "subscribe_user_id"),
			@UniqueConstraint(columnNames = "user_id") }, joinColumns = {
					@JoinColumn(name = "subscribe_user_id", unique = true, nullable = false, updatable = false) }, inverseJoinColumns = {
							@JoinColumn(name = "user_id", unique = true, nullable = false, updatable = false) })
	public Set<User> getUsersesForUserId() {
		return this.usersForUserId;
	}

	public void setUsersesForUserId(Set<User> usersForUserId) {
		this.usersForUserId = usersForUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserLikes> getUserLikes() {
		return this.userLikes;
	}

	public void setUserLikes(Set<UserLikes> userLikes) {
		this.userLikes = userLikes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Video> getVideos() {
		return this.videos;
	}

	public void setVideos(Set<Video> videos) {
		this.videos = videos;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "subscribers", catalog = "youtubeDB", uniqueConstraints = {
			@UniqueConstraint(columnNames = "subscribe_user_id"),
			@UniqueConstraint(columnNames = "user_id") }, joinColumns = {
					@JoinColumn(name = "user_id", unique = true, nullable = false, updatable = false) }, inverseJoinColumns = {
							@JoinColumn(name = "subscribe_user_id", unique = true, nullable = false, updatable = false) })
	public Set<User> getUsersForSubscribeUserId() {
		return this.usersForSubscribeUserId;
	}

	public void setUsersForSubscribeUserId(Set<User> usersesForSubscribeUserId) {
		this.usersForSubscribeUserId = usersesForSubscribeUserId;
	}

}
