package tube.entities;
// Generated Oct 6, 2016 4:59:27 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * UserLikes generated by hbm2java
 */
@Entity
@Table(name = "user_likes", catalog = "youtubeDB")
public class UserLikes implements java.io.Serializable {
	
	
	private UserLikesId id;
	private User user;
	private Video video;
	private boolean likeStatus;

	public UserLikes() {
	}
	
	public UserLikes(User user, Video video, boolean likeStatus){
		this.user = user;
		this.video = video;
		this.likeStatus = likeStatus;
	}

	public UserLikes(UserLikesId id, User user, Video video, boolean likeStatus) {
		this(user, video, likeStatus);
		this.id = id;
	
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "videoId", column = @Column(name = "video_id", nullable = false)) })
	public UserLikesId getId() {
		return this.id;
	}

	public void setId(UserLikesId id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "video_id", nullable = false, insertable = false, updatable = false)
	public Video getVideo() {
		return this.video;
	}

	public void setVideo(Video video) {
		this.video = video;
	}

	@Column(name = "likeStatus", nullable = false)
	public boolean isLikeStatus() {
		return this.likeStatus;
	}

	public void setLikeStatus(boolean likeStatus) {
		this.likeStatus = likeStatus;
	}

}
