package tube.entities;
// Generated Oct 6, 2016 4:59:27 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserLikesId generated by hbm2java
 */
@Embeddable
public class UserLikesId implements java.io.Serializable {

	private int userId;
	private int videoId;

	public UserLikesId() {
	}

	public UserLikesId(int userId, int videoId) {
		this.userId = userId;
		this.videoId = videoId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "video_id", nullable = false)
	public int getVideoId() {
		return this.videoId;
	}

	public void setVideoId(int videoId) {
		this.videoId = videoId;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UserLikesId other = (UserLikesId) obj;
		if (userId != other.userId)
			return false;
		if (videoId != other.videoId)
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + userId;
		result = prime * result + videoId;
		return result;
	}

	
	
}
