package tube.entities;
// Generated Oct 6, 2016 4:59:27 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserLikesId generated by hbm2java
 */
@Embeddable
public class UserLikesId implements java.io.Serializable {

	private int userId;
	private int videoId;

	public UserLikesId() {
	}

	public UserLikesId(int userId, int videoId) {
		this.userId = userId;
		this.videoId = videoId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "video_id", nullable = false)
	public int getVideoId() {
		return this.videoId;
	}

	public void setVideoId(int videoId) {
		this.videoId = videoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserLikesId))
			return false;
		UserLikesId castOther = (UserLikesId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getVideoId() == castOther.getVideoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getVideoId();
		return result;
	}

}
